<a href="https://colab.research.google.com/github/lucaspierref/exemplo-colaboratory/blob/main/interpolacao_quadratica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Interpolação Quadrática


In [ ]:
# Autor: Lucas Pierre D. F.
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
(x0,y0) = (0,0)
(x1,y1) = (1,1)
(x2,y2) = (4,4)

p0=(x0,y0)
p1=(x1,y1)
p2=(x2,y2)

M = np.zeros([3,3])

In [ ]:
M

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
M[0,0] = 1
M[0,1] = x0
M[0,2] = x0**2
M[1,0] = 1
M[1,1] = x1
M[1,2] = x1**2

M[2,0] = 1
M[2,1] = x2
M[2,2] = x2**2


for i in range(3):
  for j in range(3):
    M[i,j]


In [ ]:
M

array([[ 1.,  0.,  0.],
       [ 1.,  1.,  1.],
       [ 1.,  4., 16.]])

In [ ]:
y = np.array([y0,y1,y2])

In [ ]:
N = np.linalg.inv(M)

In [ ]:
print(np.matmul(M,N))

[[1.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.00000000e+00 1.38777878e-17]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
